export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  USER = 'USER',
}

export enum ACCOUTN_ACTVITY_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = "INACTIVE"
}

export enum ACCOUNT_STATUS {
  ACTIVE = 'ACTIVE',
  BLOCK = 'BLOCK',
  REPORT = 'REPORT',
  DELETE = "DELETE",
  FLAGGED = "FLAGGED"
}

export enum SELECTED_LANGUAGE {
  ENGLISH = 'ENGLISH',
  GERMAN = 'GERMAN',
  TURKISH = 'TURKISH',
  SPANISH = 'SPANISH',
}

export enum ACCOUNT_VERIFICATION_STATUS {
  VERIFIED = 'verified',
  UNVERIFIED = 'unverified',
  WAITING = 'waiting',
  REJECTED = 'rejected'
}